# docker compose --env-file .env up -d

version: "3.8"

services:
  ecommerce-be:
    image: ducvui2003/nestjs-ecommerce:1.0
    ports:
      - ${PORT}:8000
    env_file:
      - .env
    environment:
      PORT: 8000
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/ecommerce?schema=public"
      REDIS_URL: "redis://default:123@redis:6379"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ecommerce
    volumes:
      - ecommerce_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123}
    volumes:
      - ecommerce_redis_data:/data

volumes:
  ecommerce_redis_data:
  ecommerce_postgres_data:
