const SHARED_USER_REPOSITORY = 'SHARED_USER_REPOSITORY';
const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
const SUPPLIER_REPOSITORY = 'SUPPLIER_REPOSITORY';
export { SHARED_USER_REPOSITORY, CATEGORY_REPOSITORY, SUPPLIER_REPOSITORY };
