const SHARED_USER_REPOSITORY = 'SHARED_USER_REPOSITORY';
const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
const SUPPLIER_REPOSITORY = 'SUPPLIER_REPOSITORY';
const SHARED_PAYMENT_REPOSITORY = 'SHARED_PAYMENT_REPOSITORY';
const SHARED_CART_ITEM_REPOSITORY = 'SHARED_CART_ITEM_REPOSITORY';
const SHARED_PRODUCT_REPOSITORY = 'SHARED_PRODUCT_REPOSITORY';
export {
  SHARED_USER_REPOSITORY,
  CATEGORY_REPOSITORY,
  SUPPLIER_REPOSITORY,
  SHARED_PAYMENT_REPOSITORY,
  SHARED_CART_ITEM_REPOSITORY,
  SHARED_PRODUCT_REPOSITORY,
};
