# docker compose --env-file .env up -d

version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ecommerce
    volumes:
      - ${POSTGRES_VOL}:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-123}
    volumes:
      - redis_data:/data

volumes:
  redis_data:
