import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from '@/app/providers';
import { cookies } from 'next/headers';
import { Toaster } from '@/components/ui/toaster';
import { ACCESS_TOKEN, REFRESH_TOKEN } from '@/constraint/variable';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get(ACCESS_TOKEN)?.value || '';
  const refreshToken = cookieStore.get(REFRESH_TOKEN)?.value || '';
  console.log('access token', accessToken);
  console.log('refresh token', refreshToken);
  return (
    <html lang="en">
      <body>
        <Providers initToken={{ accessToken, refreshToken }}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
