name: Development

on:
  pull_request:
    branches:
      - dev
    types:
      - opened

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      nestjs: ${{ steps.filter.outputs.nestjs }}
      nextjs: ${{ steps.filter.outputs.nextjs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            nestjs:
              - 'server/**'
            nextjs:
              - 'web/**'

  build-nestjs:
    needs: detect-changes
    if: needs.detect-changes.outputs.nestjs == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: "npm"

      - name: Create env
        run: echo"${{ secrets.ENV_SERVER }}" > .env

      - name: Install dependencies
        run: npm i --force

      - name: Build NestJS
        run: npm run build

  build-nextjs:
    needs: detect-changes
    if: needs.detect-changes.outputs.nextjs == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: "npm"

      - name: Create env
        run: echo"${{ secrets.ENV_WEB }}" > .env

      - name: Install dependencies
        run: npm i --force

      - name: Build Next.js
        run: npm run build
