name: Development

on:
  pull_request:
    branches:
      - dev
    types:
      - opened

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      nestjs: ${{ steps.filter.outputs.nestjs }}
      nextjs: ${{ steps.filter.outputs.nextjs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            nestjs:
              - 'server/**'
            nextjs:
              - 'web/**'

  build-nestjs:
    needs: detect-changes
    if: needs.detect-changes.outputs.nestjs == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node_version: 22.13.1
          cache: npm
          working-directory: server

      - name: Create env
        run: echo"${{ secrets.ENV_SERVER }}" > .env
        working-directory: server

      - name: Build NestJS
        run: npm run build
        working-directory: server

  build-nextjs:
    needs: detect-changes
    if: needs.detect-changes.outputs.nextjs == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node_version: 22.13.1
          cache: npm
          working-directory: web

      - name: Create env
        run: echo"${{ secrets.ENV_WEB }}" > .env
        working-directory: web

      - name: Build Next.js
        run: npm run build
        working-directory: web
