name: Production
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      nestjs: ${{ steps.filter.outputs.nestjs }}
      nextjs: ${{ steps.filter.outputs.nextjs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            nestjs:
              - 'server/**'
            nextjs:
              - 'web/**'

  deploy-nestjs:
    if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Deploy NestJS
        run: |

          # Add your deployment script or commands here

  deploy-nextjs:
    if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Deploy NestJS
        run: |

          # Add your deployment script or commands here
