name: Notify Telegram

on:
  workflow_run:
    workflows: ["Develop", "Production"]
    types:
      - completed
      - in_progress

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🔔 *GitHub Action Notification*
            📌 Repository: ${{ github.repository }}
            🛠 Workflow: ${{ github.workflow }}
            📂 Branch: ${{ github.ref_name }}
            👤 By: ${{ github.actor }}
            🚀 Status: ${{ github.event.workflow_run.conclusion }}
            🔗 [View Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }})
