name: web-ci

on:
  pull_request:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/actions/setup-node/**"
      - ".github/workflows/web-ci.yml"
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/actions/setup-node/**"
      - ".github/workflows/web-ci.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node_version: 22.13.1
          cache: npm
          working-directory: web
      - name: Create env
        run: echo "${{ secrets.ENV_WEB }}" > .env
        working-directory: web

      - name: Build Next.js
        run: npm run build
        working-directory: web

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Parse .env and build Docker image
        run: |
          echo "${{ secrets.ENV_WEB }}" > .env
          BUILD_ARGS=""
          while IFS= read -r line || [[ -n "$line" ]]; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            BUILD_ARGS+="--build-arg $line "
          done < .env
          docker build $BUILD_ARGS -t ducvui2003/nextjs-ecommerce:latest .
          docker push ducvui2003/nextjs-ecommerce:latest
        working-directory: web
