name: Web CI

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "web/**"
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: cd web && npm install --force

      - name: Build Web (Next.js)
        run: cd web && npm run build

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web/.next
